[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Arturas Slajus <x11@arturaz.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.0"
permutohedron = "0.2.4"